version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:stable

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    parameters:
      node-version:
        type: string
    executor: linux
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Check a Node.js version
          command: node -v
      - run:
          name: Check a Yarn version
          command: yarn -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: $ yarn install
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: textlint
          command: yarn lint

workflows:
    build-and-test:
      jobs:
        - build:
            matrix:
              parameters:
                node-version: ["10.23.1", "12.16.0", "14.15.4", "15.6.0"]
